#
# Copyright Kroxylicious Authors.
#
# Licensed under the Apache Software License version 2.0, available at http://www.apache.org/licenses/LICENSE-2.0
#

---
proxy:
  address: localhost:9192
  logNetwork: false
  logFrames: false
adminHttp:
  endpoints:
    prometheus: {}
virtualClusters:
  demo:
    targetCluster:
      bootstrap_servers: localhost:9092
filters:
- type: ApiVersions
- type: BrokerAddress
#- type: ProduceRequestTransformation
#  config:
#    transformation: io.kroxylicious.proxy.internal.filter.ProduceRequestTransformationFilter$UpperCasing
