name: Sonar Scan

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  Sonar:
    runs-on: ubuntu-latest
    if: github.event.workflow_run && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: echo event
        run: cat $GITHUB_EVENT_PATH
      - name: 'Dummy'
        run: sleep 10s
        shell: bash
